### ISSUE TITLE
Save movie problem

### ISSUE THREAD

**Issue by Guyuemaple** [BenjoCowley/DataHigh#2]
It is very kind of you to share Datahigh which is really helpful. I encountered some problems when I ran it.

Here is my problem:

Following the guideline, when I save the movie of trajectory, something wrong happened. The saved movie had just a few seconds and was not intact. 

The system I used is Mac,  MATLAB 2018a.

**Comment by BenjoCowley** [comment]
Were you following the tutorials and this occurred?  Which tutorial?  I would like to debug with the same dataset.

It's likely an update to Matlab that broke this functionality.

**Comment by Guyuemaple** [comment]
The problem occurred both in the tutorial data and my own data. The version of tutorials is Oct 28, 2013. The demo data is in the /examples folder.

**Comment by BenjoCowley** [comment]
Hi, I tried to recreate your error, but my version (Matlab2018a) works, and saves a playable .mp4 on Mac. Which example were you using (ex2_visualize.m worked for me)?

Are you sure your data are trajectories, not states (i.e., lines vs. dots)?  I do not think a movie would save for states.

Thanks!
